### ISSUE TITLE
Safari Problem

### ISSUE THREAD

**Issue by macarthuror** [eshengsky/jQuery-cycleText#1]
Hello,
First of all, thanks for the incredible plugin.
I have a problem in Safari, when cycleText starts, the text doesn't show up, instead of the text you see a white box and move the rest of the text.
what can i do to fix it?

Thanks

**Comment by eshengsky** [comment]
I'm sorry I have no Mac & Safari, you can debug the plugin yourself, and may also be the compatibility problem of [Animate.css](http://daneden.github.io/animate.css/).
